"""Skill: ceiling_grid_beams — Grid of @secondary beams one Y below the ceiling, every third cell on both ax...

Generated by tools/gen_skills.py from tools/skill_specs.py. Universal —
tags.category="any" — applies to ANY room or plot of ANY building.
Hand-editing this file is fine; the generator is idempotent only for the
listed spec. If you fork, rename the id so the next regen does not stomp.
"""
from __future__ import annotations

from typing import List

from .base import AABB, Materials, Op
from . import _universal_lib as _u


def build(aabb: AABB, materials: Materials, style: str, **kwargs) -> List[Op]:
    """Generated wrapper calling `ceiling_grid` from _universal_lib."""
    return _u.ceiling_grid(aabb, materials, style, every=3)
