"""Skill: garden_flower_bed — Grass beds with rotating poppy, dandelion and blue orchid flowers.

Generated by tools/gen_skills.py from tools/skill_specs.py. Universal —
tags.category="any" — applies to ANY room or plot of ANY building.
Hand-editing this file is fine; the generator is idempotent only for the
listed spec. If you fork, rename the id so the next regen does not stomp.
"""
from __future__ import annotations

from typing import List

from .base import AABB, Materials, Op
from . import _universal_lib as _u


def build(aabb: AABB, materials: Materials, style: str, **kwargs) -> List[Op]:
    """Generated wrapper calling `garden_flowerbed` from _universal_lib."""
    return _u.garden_flowerbed(aabb, materials, style)
