"""Exterior specialist agent: design_intent.exterior → exterior_plan (shape ops).

Plans terrain + gardens + perimeter + paths around the building. Receives the
exterior door connector as a constraint to keep the front path clear.
"""
from __future__ import annotations

import json
from pathlib import Path

from .llm import call_llm_json, MODEL_WORKER
from .schema_utils import make_validator

REPO_ROOT = Path(__file__).resolve().parent.parent.parent
RAG = REPO_ROOT / "rag"
PROMPTS = Path(__file__).resolve().parent / "prompts"

def _universal_exterior_ids() -> list[str]:
    """Pull the exterior-feature ids from the generated universal-skills spec.

    Lazy import so importing exterior_agent never crashes if the generator
    has not been run yet (e.g. in a fresh clone before `python3 tools/gen_skills.py`).
    """
    try:
        from tools.gen_skills import exterior_id_list  # type: ignore
        return list(exterior_id_list())
    except Exception:
        return []


_EXTERIOR_SKILL_IDS = [
    # Legacy hand-written exterior skills
    "garden_bed", "fountain", "pergola", "gazebo",
    "perimeter_wall_with_windows", "perimeter_wall_fortified",
    "gatehouse", "stable", "dovecote", "statue_pedestal",
    "bridge_arched", "drawbridge", "moat",
    "round_tower", "square_tower", "chimney", "courtyard_well",
    # Asian standalone (ported from v5-final, tags.category="any")
    "asian_roof", "pagoda_tower", "torii_gate", "temple_eave_bracket",
    "ridge_dragon", "moon_gate",
    # Universal exterior features (generated by tools/gen_skills.py)
    *_universal_exterior_ids(),
]
# Deduplicate while preserving first-seen order.
_seen: set[str] = set()
_EXTERIOR_SKILL_IDS = [s for s in _EXTERIOR_SKILL_IDS
                       if not (s in _seen or _seen.add(s))]
del _seen


# Per-category VARIANT POOLS. Each entry is a list of (corner_features,
# front_feature, extras) tuples; the actual pick is deterministic but varies
# between different `(category, style, silhouette_id)` triples so two
# different prompts in the same category don't get identical exteriors.
# Pools are NOT random — same prompt always reproduces the same exterior.
_CASTLE_VARIANTS = [
    # (corner_skill, front_skill, ring_skill)
    ("round_tower",      "gatehouse",         "moat"),
    ("square_tower",     "gatehouse",         "moat"),
    ("round_tower",      "drawbridge",        "moat"),
    ("round_tower",      "gatehouse",         None),         # no moat — keep on a rocky outcrop
    ("square_tower",     "drawbridge",        "moat"),
]
_TEMPLE_VARIANTS = [
    # (front_focal, corner_a, corner_b)
    ("statue_pedestal",        "garden_bed",      "garden_bed"),
    ("fountain_single_basin",  "bonsai_display",  "bonsai_display"),
    ("statue_pedestal",        "karesansui_stones", "garden_bonsai_collection"),
    ("triumphal_arch_entry",   "garden_formal_parterre", "garden_zen_gravel"),
    ("statue_freestanding",    "reflective_pool", "garden_formal_parterre"),
]
_RESID_VARIANTS = [
    # (corner_skill_a, corner_skill_b, front_skill)
    ("garden_bed",                "stable",            "fountain"),
    ("garden_bed",                "pergola_arch_open", "fountain_single_basin"),
    ("garden_formal_parterre",    "garden_herb",       "fountain_tiered_classic"),
    ("garden_kitchen",            "garden_flower_bed", "pathway_with_lanterns"),
    ("garden_bonsai_collection",  "garden_zen_gravel", "pathway_stepping_stones"),
]
_GENERIC_VARIANTS = [
    ("garden_bed",                "fountain"),
    ("garden_formal_parterre",    "fountain_single_basin"),
    ("garden_flower_bed",         "statue_freestanding"),
    ("garden_herb",               "pathway_cobble"),
]


def _variant_index(pool_size: int, *keys: str) -> int:
    """Pick a deterministic but prompt-aware variant index from a pool.

    `keys` are concatenated and hashed; the hash modulo `pool_size` gives the
    selected variant. Same prompt → same exterior; different (category, style,
    silhouette_id) → different exteriors within the same category."""
    import hashlib
    seed = "|".join(k or "" for k in keys).encode("utf-8")
    h = hashlib.sha1(seed).digest()
    return int.from_bytes(h[:4], "big") % max(1, pool_size)


# Familias de estilo para el GATING DETERMINISTA del selector de features (NO
# es el LLM: aquí el pool por hash podía asignar un jardín zen a un palacio
# renacentista). Si el id de la feature es de una familia incompatible con el
# estilo del edificio, se descarta. (Las features neutras pasan siempre.)
_FEATURE_STYLE_FAMILY = {
    "asian": (("torii", "paifang", "pagoda", "zen", "bonsai", "koi", "lotus",
               "moon_gate", "karesansui", "lantern_path", "ridge_dragon",
               "prayer_wheel", "bamboo", "incense"),
              {"japanese", "chinese", "fantasy"}),
    "classical": (("corinthian", "doric", "ionic", "pediment", "triumphal",
                   "balustrade", "amphora", "urn", "obelisk", "acroterion", "laurel"),
                  {"renaissance", "mediterranean", "modern"}),
    "medieval": (("moat", "gatehouse", "drawbridge", "fortified", "parapet",
                  "brazier", "armor", "weapon", "portcullis", "battlement"),
                 {"medieval", "castle", "fortress", "rustic", "fantasy", "gothic"}),
}


def _skill_fits_style(skill_id: str, style: str) -> bool:
    """True si la feature es neutra o su familia es compatible con el estilo."""
    sid = (skill_id or "").lower()
    st = (style or "").lower()
    for _fam, (kws, compatible) in _FEATURE_STYLE_FAMILY.items():
        if any(k in sid for k in kws):
            return st in compatible
    return True


def select_exterior_features(category, style, silhouette_id,
                             building_aabb, site_aabb) -> list[dict]:
    """Choose WHICH exterior features a building gets, by category/style.

    The choice is *deterministic in the prompt* — `hash(category, style,
    silhouette_id)` picks one variant from a per-category pool — but VARIES
    between prompts. Two different castles get different exterior
    compositions; the same castle prompt is reproducible across runs.
    """
    if not (isinstance(building_aabb, list) and len(building_aabb) == 6
            and isinstance(site_aabb, list) and len(site_aabb) == 6):
        return []
    bx0, by0, bz0, bx1, by1, bz1 = building_aabb
    sx0, sy0, sz0, sx1, sy1, sz1 = site_aabb
    y = sy0
    cat = (category or "").lower()
    st = (style or "").lower()
    sil = (silhouette_id or "").lower()
    feats: list[dict] = []

    def add(skill, aabb):
        if skill is None:
            return
        if not _skill_fits_style(skill, style):
            return                       # gating de coherencia (pool determinista)
        x0, z0, x1, z1 = aabb
        x0, x1 = max(sx0, min(x0, x1)), min(sx1, max(x0, x1))
        z0, z1 = max(sz0, min(z0, z1)), min(sz1, max(z0, z1))
        if x1 - x0 >= 2 and z1 - z0 >= 2:
            feats.append({"skill_hint": skill, "name": skill,
                          "aabb": [x0, y, z0, x1, by1, z1]})

    c = 3                                        # corner feature size
    corners = [(sx0, sz0), (sx1 - c, sz0), (sx0, sz1 - c), (sx1 - c, sz1 - c)]
    fcx = (bx0 + bx1) // 2
    front_center = [fcx - 2, sz0, fcx + 2, bz0]
    ring = [sx0, sz0, sx1, sz1]

    is_castle = cat in ("castle", "fortress", "keep") or "keep" in sil
    is_temple = cat in ("temple", "monument", "shrine", "chapel")
    is_resid = cat in ("residential", "house", "villa", "mansion", "cottage",
                       "tavern")

    if is_castle:
        idx = _variant_index(len(_CASTLE_VARIANTS), cat, st, sil)
        corner_skill, front_skill, ring_skill = _CASTLE_VARIANTS[idx]
        add("perimeter_wall_fortified", ring)
        add(front_skill, front_center)
        add(ring_skill, ring)
        for (cx, cz) in corners:
            add(corner_skill, [cx, cz, cx + c, cz + c])
    elif is_temple:
        idx = _variant_index(len(_TEMPLE_VARIANTS), cat, st, sil)
        front, ca, cb = _TEMPLE_VARIANTS[idx]
        add(front, front_center)
        add(ca, [corners[0][0], corners[0][1],
                  corners[0][0] + c, corners[0][1] + c])
        add(cb, [corners[3][0], corners[3][1],
                  corners[3][0] + c, corners[3][1] + c])
    elif is_resid:
        idx = _variant_index(len(_RESID_VARIANTS), cat, st, sil)
        ca, cb, front = _RESID_VARIANTS[idx]
        add(ca, [corners[0][0], corners[0][1],
                  corners[0][0] + c, corners[0][1] + c])
        add(cb, [corners[3][0], corners[3][1],
                  corners[3][0] + c + 1, corners[3][1] + c])
        add(front, front_center)
    else:
        idx = _variant_index(len(_GENERIC_VARIANTS), cat, st, sil)
        garden, front = _GENERIC_VARIANTS[idx]
        add(garden, [corners[0][0], corners[0][1],
                      corners[0][0] + c, corners[0][1] + c])
        add(front, front_center)
    return feats


def _load_exterior_skills() -> list[dict]:
    out = []
    for sid in _EXTERIOR_SKILL_IDS:
        f = RAG / "skills" / f"{sid}.json"
        if not f.exists():
            continue
        d = json.loads(f.read_text(encoding="utf-8"))
        brief = {
            "id":           d["id"],
            "name":         d.get("name", d["id"]),
            "description":  (d.get("description") or "")[:200],
            "typical_dims": d.get("typical_dimensions", {}),
        }
        if d.get("style_affinity"):     # nota de estilo para que el LLM valore
            brief["style_affinity"] = d["style_affinity"]
        out.append(brief)
    return out


def _style_pack_compact(style: str) -> dict:
    f = RAG / "styles" / f"{style}.json"
    if not f.exists():
        return {"id": style, "palette": {}, "signature_elements": []}
    d = json.loads(f.read_text(encoding="utf-8"))
    palette = d.get("palette", {})
    flat = {k: (v[0] if isinstance(v, list) and v else v) for k, v in palette.items()}
    return {
        "id":                 d["id"],
        "palette":            flat,
        "signature_elements": d.get("signature_elements", [])[:6],
    }


def _room_plan_validator():
    return make_validator("room_plan.schema.json")


def _exterior_door(design_intent: dict) -> dict | None:
    for d in design_intent.get("connectors", {}).get("doors", []):
        if "outside" in d.get("between", []):
            return d
    return None


def plan_exterior(design_intent: dict, *, model: str = MODEL_WORKER,
                   max_attempts: int = 4,
                   fallback_on_failure: bool = False) -> dict:
    """Produce the exterior plan for a design_intent.

    Gym constraint: NO silent fallback. Retries up to max_attempts times
    with feedback, then raises. The user wants every variety-affecting
    decision to trace to an LLM call. fallback_on_failure default False.
    """
    style = design_intent["style"]
    site_aabb = design_intent.get("site_aabb")
    building_aabb = design_intent.get("building_aabb")
    features = design_intent.get("exterior", {}).get("features", [])
    ext_door = _exterior_door(design_intent)

    # 2026-05-30 RELAJADO: dropped `style_pack` (RAG-B). The exterior_agent
    # only needs the SKILL candidates + feature placements + style name to
    # produce ops; injecting the full style palette pushed every exterior
    # to look the same. style alone gives the LLM enough signal.
    context = {
        "site_aabb":         site_aabb,
        "building_aabb":     building_aabb,
        "style":             style,
        "features":          features,
        "exterior_door":     ext_door,
        "candidate_skills":  _load_exterior_skills(),
    }
    system = (PROMPTS / "exterior.md").read_text(encoding="utf-8")
    user_payload = json.dumps(context, ensure_ascii=False, indent=2)

    validator = _room_plan_validator()

    last_err = None
    for attempt in range(max_attempts):
        try:
            doc = call_llm_json(system=system, user=user_payload, model=model,
                                max_tokens=2048, temperature=0.5)
        except Exception as e:
            last_err = e
            if attempt < max_attempts - 1:
                continue
            if fallback_on_failure:
                return _fallback_plan(design_intent)
            raise RuntimeError(
                f"exterior_agent LLM call failed after {max_attempts} "
                f"attempts: {e}") from e

        # Force the role/room_id even if the model strayed; strip None
        # values from optional shape-op fields (schema doesn't accept null).
        doc["room_id"] = "exterior"
        doc["role"] = "exterior"
        if not isinstance(doc.get("style"), str):
            doc["style"] = style
        for op in doc.get("ops", []) or []:
            if not isinstance(op, dict):
                continue
            for k in list(op.keys()):
                if op[k] is None and k in ("fill", "floor", "ceiling", "level",
                                              "hollow", "style", "kwargs"):
                    del op[k]

        errs = list(validator.iter_errors(doc))
        if not errs:
            return doc

        last_err = errs[0]
        if attempt < max_attempts - 1:
            user_payload += (
                f"\n\n[VALIDATION ERROR — retry now]\n"
                f"Your previous output failed schema validation:\n"
                f"  {last_err.message[:300]}\n"
                f"Return ONLY the corrected JSON.")
            continue
        if fallback_on_failure:
            return _fallback_plan(design_intent)
        raise ValueError(
            f"exterior_agent output invalid after {max_attempts} "
            f"attempts: {last_err.message[:300]}")

    raise RuntimeError("unreachable")


_TREE_LEAF = {"medieval": "minecraft:oak_leaves", "rustic": "minecraft:oak_leaves",
              "fantasy": "minecraft:dark_oak_leaves", "gothic": "minecraft:spruce_leaves",
              "japanese": "minecraft:dark_oak_leaves", "chinese": "minecraft:oak_leaves",
              "mediterranean": "minecraft:jungle_leaves", "renaissance": "minecraft:oak_leaves",
              "modern": "minecraft:birch_leaves", "minimalist": "minecraft:birch_leaves"}
_TREE_LOG = {"birch": "minecraft:birch_log", "jungle": "minecraft:jungle_log",
             "dark_oak": "minecraft:dark_oak_log", "spruce": "minecraft:spruce_log"}
_FLOWERS = ["minecraft:poppy", "minecraft:dandelion", "minecraft:oxeye_daisy",
            "minecraft:blue_orchid", "minecraft:azure_bluet"]


_STYLE_FENCE = {
    "modern": "minecraft:iron_bars", "minimalist": "minecraft:iron_bars",
    "fantasy": "minecraft:dark_oak_fence", "gothic": "minecraft:dark_oak_fence",
    "japanese": "minecraft:spruce_fence", "chinese": "minecraft:spruce_fence",
}
_STYLE_LANTERN = {"gothic": "minecraft:soul_lantern", "fantasy": "minecraft:soul_lantern"}


def _exterior_decor(site, building, style, door=None) -> list:
    """Decoración determinista del apron (site menos edificio) — da vida al
    exterior, antes era hierba pelada. Sigue la lógica del agente: primitivas
    deterministas (mismo prompt → mismo apron), todo en el suelo del apron y
    fuera del footprint del edificio → anclado (el aligner no lo poda).

    Capas (estilo "lush" del landscape de TFGv2):
      * árboles en las esquinas + flores dispersas,
      * SETO perimetral de 2 de alto en el borde del solar (con hueco para el
        camino de entrada),
      * FAROLAS (poste de valla + linterna) en las esquinas del apron,
      * BANCOS (escaleras enfrentadas) flanqueando la puerta.
    """
    if not (isinstance(site, list) and len(site) == 6):
        return []
    sx0, sy0, sz0, sx1, _sy1, sz1 = site
    bx0, _, bz0, bx1, _, bz1 = building if (isinstance(building, list)
                                             and len(building) == 6) else site
    y = sy0 + 1
    leaf = _TREE_LEAF.get(style, "minecraft:oak_leaves")
    log = next((v for k, v in _TREE_LOG.items() if k in leaf), "minecraft:oak_log")
    fence = _STYLE_FENCE.get(style, "minecraft:oak_fence")
    lantern = _STYLE_LANTERN.get(style, "minecraft:lantern")
    ops = []

    def in_building(x, z):
        return (bx0 - 1) <= x <= bx1 and (bz0 - 1) <= z <= bz1

    # Hueco del camino: celda de borde más cercana a la puerta (no tapiar la
    # entrada con el seto).
    gate = None
    gate_out = (0, 1)            # dirección hacia el apron (normal de la puerta)
    if door and isinstance(door.get("at"), list) and len(door["at"]) == 3:
        gx, _gy, gz = door["at"]
        gate = (gx, gz)
        gate_out = {"n": (0, -1), "s": (0, 1), "e": (1, 0),
                    "w": (-1, 0)}.get(door.get("facing", "s"), (0, 1))

    def near_gate(x, z) -> bool:
        return gate is not None and abs(x - gate[0]) + abs(z - gate[1]) <= 2

    def tree(tx, tz):
        if in_building(tx, tz) or not (sx0 < tx < sx1 - 1 and sz0 < tz < sz1 - 1):
            return
        for dy in range(4):                              # trunk
            ops.append({"kind": "place", "at": [tx, y + dy, tz], "block": log})
        ops.append({"kind": "fill",                       # leaf blob
                    "aabb": [tx - 1, y + 3, tz - 1, tx + 2, y + 5, tz + 2],
                    "block": leaf})
        ops.append({"kind": "place", "at": [tx, y + 5, tz], "block": leaf})

    # a tree near each apron corner that has room
    for (tx, tz) in [(sx0 + 1, sz0 + 1), (sx1 - 2, sz0 + 1),
                     (sx0 + 1, sz1 - 2), (sx1 - 2, sz1 - 2)]:
        tree(tx, tz)

    # scattered flowers on the apron grass
    for x in range(sx0, sx1):
        for z in range(sz0, sz1):
            if in_building(x, z):
                continue
            if (x * 7 + z * 3) % 5 == 0:                  # sparse, deterministic
                ops.append({"kind": "place", "at": [x, y, z],
                            "block": _FLOWERS[(x + z) % len(_FLOWERS)]})

    # SETO perimetral (2 de alto) en el borde del solar, con hueco en la puerta.
    def hedge(x, z):
        if in_building(x, z) or near_gate(x, z):
            return
        ops.append({"kind": "place", "at": [x, y, z], "block": leaf})
        ops.append({"kind": "place", "at": [x, y + 1, z], "block": leaf})

    for x in range(sx0, sx1):
        hedge(x, sz0); hedge(x, sz1 - 1)
    for z in range(sz0 + 1, sz1 - 1):
        hedge(sx0, z); hedge(sx1 - 1, z)

    # FAROLAS en las esquinas del apron (poste de valla + linterna arriba).
    for (lx, lz) in [(sx0 + 1, sz0 + 1), (sx1 - 2, sz0 + 1),
                     (sx0 + 1, sz1 - 2), (sx1 - 2, sz1 - 2)]:
        if in_building(lx, lz):
            continue
        for dy in range(3):
            ops.append({"kind": "place", "at": [lx, y + dy, lz], "block": fence})
        ops.append({"kind": "place", "at": [lx, y + 3, lz], "block": lantern})

    # BANCOS flanqueando el camino, desplazados al apron según la normal de la
    # puerta (perpendicular = eje del muro), enfrentados hacia el camino.
    if gate is not None:
        gx, gz = gate
        odx, odz = gate_out
        ox, oz = gx + odx * 2, gz + odz * 2          # 2 pasos al apron
        perp = (odz, odx)                             # eje del muro
        for sign, facing in ((-1, "east" if odz else "south"),
                             (1, "west" if odz else "north")):
            bx_, bz_ = ox + perp[0] * sign * 2, oz + perp[1] * sign * 2
            if not in_building(bx_, bz_) and sx0 <= bx_ < sx1 and sz0 <= bz_ < sz1:
                ops.append({"kind": "place", "at": [bx_, y, bz_],
                            "block": f"minecraft:oak_stairs[facing={facing}]"})
    return ops


def _fallback_plan(design_intent: dict) -> dict:
    """Deterministic minimal exterior: grass ground + cobblestone path to door.

    Used when the LLM call repeatedly fails. Schema-valid by construction.
    """
    style = design_intent["style"]
    site = design_intent.get("site_aabb") or [0, 0, 0, 1, 1, 1]
    bldg = design_intent.get("building_aabb")
    ops = [
        # Grass ground layer along the floor of the site
        {"kind": "rect",
         "aabb": [site[0], site[1], site[2], site[3], site[1]+1, site[5]],
         "axis": "y", "level": site[1],
         "block": "minecraft:grass_block"},
    ]
    # Materialize the SELECTED exterior features as skill ops (each exterior
    # feature has a build() module). This is what gives the deterministic
    # exterior its variety — castle walls/towers/moat, villa garden/fountain —
    # instead of bare grass when the LLM fails.
    _valid = set(_EXTERIOR_SKILL_IDS)
    for feat in (design_intent.get("exterior", {}).get("features") or []):
        sid = feat.get("skill_hint") or feat.get("role")
        a = feat.get("aabb")
        if sid in _valid and isinstance(a, list) and len(a) == 6:
            ops.append({"kind": "skill", "skill_id": sid,
                         "aabb": [int(v) for v in a], "style": style})
    # A 1-block-wide cobblestone path from the exterior door outward 3 blocks
    door = _exterior_door(design_intent)
    if door and bldg:
        x, y, z = door["at"]
        facing = door.get("facing", "n")
        dx, dz = {"n": (0, -1), "s": (0, 1), "e": (1, 0), "w": (-1, 0)}.get(facing, (0, 1))
        for step in range(1, 4):
            ops.append({"kind": "place",
                         "at": [x + dx*step, site[1], z + dz*step],
                         "block": "minecraft:cobblestone"})
    # greenery + hedge + lampposts + benches in the apron (lush landscape)
    ops.extend(_exterior_decor(site, bldg, style, door=door))
    return {
        "room_id": "exterior",
        "role":    "exterior",
        "aabb":    site,
        "style":   style,
        "patterns_applied": ["public-outdoor-room"],
        "skill_chosen":     None,
        "ops":              ops,
        "notes":            "deterministic fallback (LLM failed or skipped)",
    }


if __name__ == "__main__":
    di = {
        "style": "medieval",
        "site_aabb":      [-3, 0, -3,  9, 5, 8],
        "building_aabb":  [0, 0, 0,  6, 5, 5],
        "exterior": {"features": [
            {"role": "garden_bed", "aabb": [-3, 0, -3, 0, 1, 8], "skill_hint": "garden_bed"}
        ]},
        "connectors": {"doors": [
            {"id":"d1","between":["outside","entry-1"],"at":[3,1,0],"facing":"s"}
        ], "windows": [], "staircases": []},
    }
    plan = plan_exterior(di)
    print(json.dumps(plan, indent=2, ensure_ascii=False))
