"""Universal-skill code-generator.

Reads `tools.skill_specs.SKILLS` and emits two files per spec:

    pipeline/skills/<id>.py     a thin wrapper that calls a primitive in
                                 pipeline.skills._universal_lib
    rag/skills/<id>.json        the RAG-A entry (schema-validated)

The generator is **idempotent**: rerunning it overwrites the same files with
identical content (modulo the regeneration marker). Hand-written skills are
NOT touched — only the IDs declared in SKILLS are written.

Run:

    python3 tools/gen_skills.py [--dry-run] [--check-only]

Cross-ref integration: every emitted JSON has `tags.category="any"`, so
room_agent and exterior_agent see it for any building. The exterior_agent
hardcoded list (`_EXTERIOR_SKILL_IDS`) is extended separately by
`tools.gen_skills.exterior_id_list()`.
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

# allow running from repo root
REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT))

from tools.skill_specs import ALL_STYLES, SKILLS  # noqa: E402


PY_TEMPLATE = '''"""Skill: {sid} — {short_desc}

Generated by tools/gen_skills.py from tools/skill_specs.py. Universal —
tags.category="any" — applies to ANY room or plot of ANY building.
Hand-editing this file is fine; the generator is idempotent only for the
listed spec. If you fork, rename the id so the next regen does not stomp.
"""
from __future__ import annotations

from typing import List

from .base import AABB, Materials, Op
from . import _universal_lib as _u


def build(aabb: AABB, materials: Materials, style: str, **kwargs) -> List[Op]:
    """Generated wrapper calling `{recipe}` from _universal_lib."""
    return _u.{recipe}(aabb, materials, style{params_str})
'''


def _format_params(params: dict) -> str:
    """Render a params dict as `, key=value, key2=value2` (keyword args)."""
    if not params:
        return ""
    parts = []
    for k, v in params.items():
        parts.append(f"{k}={_format_value(v)}")
    return ", " + ", ".join(parts)


def _format_value(v) -> str:
    if v is None:
        return "None"
    if isinstance(v, str):
        return repr(v)
    if isinstance(v, (int, float, bool)):
        return repr(v)
    if isinstance(v, (list, tuple)):
        inside = ", ".join(_format_value(x) for x in v)
        return f"({inside},)" if isinstance(v, tuple) else f"[{inside}]"
    raise TypeError(f"unsupported param value: {v!r}")


def _short_desc(spec: dict) -> str:
    d = spec.get("description", "")
    return d if len(d) < 80 else d[:77] + "..."


def py_file(spec: dict) -> str:
    return PY_TEMPLATE.format(
        sid=spec["id"],
        short_desc=_short_desc(spec),
        recipe=spec["recipe"],
        params_str=_format_params(spec.get("params") or {}),
    )


def json_entry(spec: dict) -> dict:
    return {
        "id": spec["id"],
        "name": spec["name"],
        "kind": spec["kind"],
        "description": spec["description"],
        "typical_dimensions": {
            "min": spec["min"],
            "preferred": spec["preferred"],
            "max": spec["max"],
        },
        "tags": {
            "category": "any",
            "style": list(ALL_STYLES),
        },
        "python_skill_signature": (
            f"pipeline.skills.{spec['id']}.build(aabb: AABB, "
            "materials: Materials, style: str, **kwargs) -> list[Op]"
        ),
        "skill_category": spec["skill_category"],
        "schema_version": "2.0",
    }


def exterior_id_list() -> list[str]:
    """All universal skill IDs whose family is exterior-oriented.

    Used by `pipeline.agents.exterior_agent` to extend `_EXTERIOR_SKILL_IDS`.
    """
    return sorted({s["id"] for s in SKILLS
                    if s["skill_category"] == "exterior_feature"})


def main(argv=None):
    parser = argparse.ArgumentParser()
    parser.add_argument("--dry-run", action="store_true",
                         help="show what would be written")
    parser.add_argument("--check-only", action="store_true",
                         help="exit non-zero if any file would change")
    args = parser.parse_args(argv)

    py_dir = REPO_ROOT / "pipeline" / "skills"
    json_dir = REPO_ROOT / "rag" / "skills"

    py_dir.mkdir(parents=True, exist_ok=True)
    json_dir.mkdir(parents=True, exist_ok=True)

    n_py = n_json = 0
    changed = False
    for spec in SKILLS:
        sid = spec["id"]
        py_path = py_dir / f"{sid}.py"
        json_path = json_dir / f"{sid}.json"

        py_content = py_file(spec)
        json_content = json.dumps(json_entry(spec), indent=2, ensure_ascii=False) + "\n"

        if args.dry_run or args.check_only:
            if not py_path.exists() or py_path.read_text() != py_content:
                print(f"[would write] {py_path}")
                changed = True
            if not json_path.exists() or json_path.read_text() != json_content:
                print(f"[would write] {json_path}")
                changed = True
            continue

        py_path.write_text(py_content)
        json_path.write_text(json_content)
        n_py += 1
        n_json += 1

    if args.check_only:
        sys.exit(1 if changed else 0)
    if args.dry_run:
        print(f"dry-run: {sum(1 for _ in SKILLS)} specs scanned")
        return

    print(f"wrote {n_py} Python files + {n_json} JSON files into "
           f"{py_dir} and {json_dir}")
    print(f"({len(SKILLS)} specs total)")


if __name__ == "__main__":
    main()
