"""Spec list for the universal-skills generator.

Each entry describes ONE universal skill (`tags.category="any"`) that the
pipeline's room_agent or exterior_agent may pick for ANY building type.
The generator (`tools/gen_skills.py`) reads SKILLS and emits two files
per entry:

    pipeline/skills/<id>.py     thin wrapper calling a primitive in
                                 pipeline/skills/_universal_lib.py
    rag/skills/<id>.json        RAG entry validating against
                                 rag/schema/skill_entry.schema.json

Spec fields (all required unless noted):

    id              kebab-friendly snake_case skill id (also Python module name)
    name            human-readable display name
    description     ≥ 10 char description for the RAG entry
    kind            'room' | 'furniture' | 'structural' | 'exterior' | 'decorative'
    family          informal grouper (floor/wall/ceiling/...) — also surfaces in
                    skill_category mapping
    skill_category  v4 BOT category — typically 'room_decoration' or
                    'exterior_feature'
    min, preferred, max
                    typical_dimensions in (w, h, d)
    recipe          name of a function in pipeline.skills._universal_lib
    params (opt)    dict of keyword args baked into the wrapper's call

Universality contract: the generated skills MUST NOT assume a specific
category or style. They only consume the AABB and Materials they are given.
"""
from __future__ import annotations

# ── shared dimension presets ────────────────────────────────────────────────
ROOM_DIMS = {"min": [4, 3, 4], "preferred": [8, 4, 8], "max": [16, 9, 16]}
SMALL_ROOM_DIMS = {"min": [3, 3, 3], "preferred": [6, 4, 6], "max": [12, 6, 12]}
EXT_PLOT_DIMS = {"min": [5, 3, 5], "preferred": [9, 5, 9], "max": [20, 8, 20]}
PATH_DIMS = {"min": [3, 2, 3], "preferred": [10, 2, 5], "max": [30, 3, 12]}
ROOF_TOP_DIMS = {"min": [3, 2, 3], "preferred": [6, 3, 6], "max": [12, 5, 12]}

# All styles the project supports — every skill is style-agnostic, so we list
# them all so the LLM retrieval matches regardless of style filter.
ALL_STYLES = ["medieval", "rustic", "fantasy", "gothic", "renaissance",
              "modern", "minimalist", "japanese", "chinese", "mediterranean"]


def _room(name_id, name, desc, recipe, *, params=None, dims=None, kind="decorative"):
    return {
        "id": name_id, "name": name, "description": desc,
        "kind": kind, "family": recipe.split("_")[0],
        "skill_category": "room_decoration",
        **(dims or ROOM_DIMS), "recipe": recipe, "params": params or {},
    }


def _ext(name_id, name, desc, recipe, *, params=None, dims=None, kind="exterior"):
    return {
        "id": name_id, "name": name, "description": desc,
        "kind": kind, "family": recipe.split("_")[0],
        "skill_category": "exterior_feature",
        **(dims or EXT_PLOT_DIMS), "recipe": recipe, "params": params or {},
    }


def _roof(name_id, name, desc, recipe, *, params=None, kind="decorative"):
    return {
        "id": name_id, "name": name, "description": desc,
        "kind": kind, "family": "roof",
        "skill_category": "exterior_feature",
        **ROOF_TOP_DIMS, "recipe": recipe, "params": params or {},
    }


SKILLS: list[dict] = [
    # ── FLOOR DECORATION (14) ────────────────────────────────────────────────
    _room("floor_pattern_checker", "Checkerboard tile floor",
          "Two-tone checkerboard tile pattern across the interior floor — alternating @primary and @accent blocks. Works in any room category. Reads as classical foyer or palace hall.",
          "floor_checker"),
    _room("floor_pattern_dark_checker", "Dark-toned checker floor",
          "Checkerboard with darker @secondary and @accent — a sombre cloister or gothic hall floor.",
          "floor_checker", params={"a_block": "@secondary", "b_block": "@accent"}),
    _room("floor_pattern_stripe_x", "Stripe floor along width",
          "Alternating stripes running along the room's X axis. Reads as plank flooring or parquet stripe.",
          "floor_stripes", params={"axis": "x"}),
    _room("floor_pattern_stripe_z", "Stripe floor along depth",
          "Alternating stripes running along the room's Z axis. Use to draw the eye toward a focal wall.",
          "floor_stripes", params={"axis": "z"}),
    _room("floor_pattern_herringbone", "Herringbone-effect floor",
          "Two-tone stripe pattern with a tighter pitch evoking a herringbone hardwood floor.",
          "floor_stripes", params={"a_block": "@primary", "b_block": "@floor"}),
    _room("floor_pattern_mandala", "Concentric mandala floor",
          "Concentric rings of three blocks centered on the room — outer ring @primary, inner ring @accent, core @secondary. Reads as oriental medallion.",
          "floor_concentric"),
    _room("floor_pattern_persian_rug", "Persian rug medallion",
          "Concentric rings with @carpet at core — evokes a hand-knotted Persian rug centered in the room.",
          "floor_concentric", params={"outer": "@accent", "inner": "@carpet", "core": "@accent"}),
    _room("floor_pattern_stone_circle", "Stone circle medallion",
          "Concentric rings of stone-family blocks evoking a temple medallion in the floor.",
          "floor_concentric", params={"outer": "@secondary", "inner": "@primary", "core": "@accent"}),
    _room("floor_pattern_parquet", "Parquet floor",
          "Stripe pattern using @primary and @floor — classical wood parquet.",
          "floor_stripes", params={"a_block": "@primary", "b_block": "@floor", "axis": "x"}),
    _room("floor_pattern_runic_circle", "Runic circle inset",
          "Concentric rings evoking a runic ritual circle in a sanctuary or tower.",
          "floor_concentric", params={"outer": "@secondary", "inner": "@accent", "core": "@light"}),
    _room("floor_pattern_carpet_inset", "Central carpet inset",
          "Smaller rectangle of @carpet inset 2 cells from each wall — a defined seating area in a larger room.",
          "floor_center_inset", params={"base": "@floor", "inset_blk": "@carpet", "inset": 2}),
    _room("floor_pattern_dais", "Raised dais inset",
          "Solid @accent dais inset from the walls — a focal raised area at room centre.",
          "floor_center_inset", params={"base": "@floor", "inset_blk": "@accent", "inset": 2}),
    _room("floor_pattern_zen_inset", "Zen gravel inset",
          "Gravel inset rectangle on a wooden floor — a meditative zen patch.",
          "floor_center_inset", params={"base": "@floor", "inset_blk": "minecraft:gravel", "inset": 2}),
    _room("floor_pattern_obsidian_seal", "Obsidian seal inset",
          "Dark central inset of @secondary — a sealed glyph at room centre.",
          "floor_center_inset", params={"base": "@floor", "inset_blk": "@secondary", "inset": 2}),

    # ── WALL DECORATION (16) ─────────────────────────────────────────────────
    _room("wall_band_cornice", "Cornice band",
          "Single-Y horizontal band of @accent at three quarters of wall height — runs around the room perimeter. Classical cornice.",
          "wall_band", params={"y_frac": 0.75}),
    _room("wall_band_chair_rail", "Chair-rail band",
          "Horizontal band of @accent at chair-rail height (low) around the perimeter.",
          "wall_band", params={"y_frac": 0.35}),
    _room("wall_band_dado", "Dado band",
          "Two-block-high band: combine with chair_rail for a panelled dado.",
          "wall_band", params={"y_frac": 0.5}),
    _room("wall_band_frieze", "Decorative frieze",
          "High accent frieze just below the ceiling — runs around the perimeter.",
          "wall_band", params={"y_frac": 0.85, "block": "@accent"}),
    _room("wall_calligraphy_band", "Calligraphy band",
          "High band of @secondary evoking an Arabic/Chinese calligraphy strip near the ceiling.",
          "wall_band", params={"y_frac": 0.85, "block": "@secondary"}),
    _room("wall_pilasters_4", "Pilaster columns every 4",
          "Vertical accent pilasters at every fourth cell along all four interior walls.",
          "wall_pilasters", params={"every": 4}),
    _room("wall_pilasters_3", "Pilaster columns every 3",
          "Tighter pilaster spacing — every third cell — for a more ornate Renaissance hall.",
          "wall_pilasters", params={"every": 3}),
    _room("wall_pilasters_classical", "Classical pilasters",
          "Wider pilaster spacing of @secondary — sober temple or basilica feel.",
          "wall_pilasters", params={"every": 5, "block": "@secondary"}),
    _room("wall_arched_recess", "Arched wall recesses",
          "Accent markers at chest height on long walls evoking shallow arched recesses.",
          "wall_niche", params={"count": 3}),
    _room("wall_niche_pair", "Pair of niches",
          "Two accent niches on each long wall — places for sculpture or relics.",
          "wall_niche", params={"count": 2}),
    _room("wall_lattice_screen", "Lattice screen wall",
          "Decorative lattice of @glass_pane around the room mid-band.",
          "wall_lattice", params={"block": "@glass_pane"}),
    _room("wall_lattice_oak", "Wooden lattice band",
          "Lattice band of @fence forming a screen on every wall.",
          "wall_lattice", params={"block": "@fence"}),
    _room("wall_panel_low", "Low wainscot panels",
          "Low panelling band of @secondary along the perimeter.",
          "wall_band", params={"y_frac": 0.3, "block": "@secondary"}),
    _room("wall_panel_high", "High panel band",
          "High band of @primary with detail — wood panel rail near the ceiling.",
          "wall_band", params={"y_frac": 0.7, "block": "@primary"}),
    _room("wall_relief_iron", "Iron relief band",
          "Iron-bar relief band running around the room — industrial or gothic.",
          "wall_band", params={"y_frac": 0.6, "block": "minecraft:iron_bars"}),
    _room("wall_relief_gold", "Gilt frieze band",
          "Gold-block frieze running around the perimeter — palatial / imperial.",
          "wall_band", params={"y_frac": 0.75, "block": "minecraft:gold_block"}),

    # ── CEILING DECORATION (12) ──────────────────────────────────────────────
    _room("ceiling_grid_beams", "Cross-beam ceiling grid",
          "Grid of @secondary beams one Y below the ceiling, every third cell on both axes.",
          "ceiling_grid", params={"every": 3}),
    _room("ceiling_grid_fine", "Fine ceiling grid",
          "Every-2 grid of beams — denser coffer-like pattern.",
          "ceiling_grid", params={"every": 2}),
    _room("ceiling_coffer_panels", "Coffered ceiling",
          "Coffered ceiling: 3x3 panels with @secondary edge frames.",
          "ceiling_coffer"),
    _room("ceiling_radial_beams", "Radial ceiling beams",
          "Four radial beams from centre out to each wall, one Y below the ceiling.",
          "ceiling_radial"),
    _room("ceiling_chandelier", "Central chandelier",
          "Vertical drop from the ceiling centre: accent top, fence chain, and lantern.",
          "ceiling_center_fixture", params={"drop": 2}),
    _room("ceiling_pendant_long", "Long pendant",
          "Tall pendant drop (3 cells) from ceiling centre.",
          "ceiling_center_fixture", params={"drop": 3}),
    _room("ceiling_pendant_short", "Short pendant",
          "Short pendant drop (1 cell) for low rooms.",
          "ceiling_center_fixture", params={"drop": 1}),
    _room("ceiling_lantern_drop", "Lantern drop fixture",
          "Plain lantern hanging by a chain — utilitarian fixture for taverns or workshops.",
          "ceiling_center_fixture", params={"top": "@secondary", "chain": "@fence", "light": "@lantern", "drop": 1}),
    _room("ceiling_skylight_square", "Square skylight",
          "Glass square inset in the ceiling centre — lets in light from above.",
          "ceiling_skylight"),
    _room("ceiling_smoke_vent", "Smoke vent opening",
          "Central opening framed by @secondary — a vent for hearths and kitchens.",
          "ceiling_skylight", params={"glass": "@secondary"}),
    _room("ceiling_rosette", "Decorative ceiling rosette",
          "Single accent rosette block at ceiling centre with radial beams.",
          "ceiling_radial", params={"block": "@accent"}),
    _room("ceiling_hanging_plants", "Hanging plants from ceiling",
          "Pendant of leaves hanging from a chain at the centre.",
          "ceiling_center_fixture", params={"top": "@accent", "chain": "@fence", "light": "minecraft:oak_leaves", "drop": 2}),

    # ── CORNER ELEMENTS (10) ─────────────────────────────────────────────────
    _room("corner_column", "Decorative corner columns",
          "Four interior corner columns of @accent capped with @light.",
          "corner_posts"),
    _room("corner_statue_niche", "Corner statue niches",
          "Four corner columns of @secondary with no light cap — austere niche markers.",
          "corner_posts", params={"block": "@secondary", "cap": None}),
    _room("corner_lamp_post", "Corner lamp posts",
          "Four corner posts capped with lanterns — a lit corner motif.",
          "corner_posts", params={"block": "@fence", "cap": "@lantern"}),
    _room("corner_plant", "Corner planters",
          "Single accent block at each of the four floor corners — placeholder for a planter.",
          "corner_accents", params={"block": "@flower_pot"}),
    _room("corner_brazier", "Corner braziers",
          "Four corner posts capped with light — evoking smoldering braziers.",
          "corner_posts", params={"block": "@accent", "cap": "@light", "height": 2}),
    _room("corner_water_basin", "Corner water basins",
          "Four corner accents of cobblestone wall — small basins for ablutions.",
          "corner_accents", params={"block": "minecraft:cobblestone_wall"}),
    _room("corner_pedestal", "Corner pedestals",
          "Single column at each corner capped with @accent.",
          "corner_posts", params={"block": "@secondary", "cap": "@accent", "height": 3}),
    _room("corner_torch", "Corner wall torches",
          "Lantern at each of the four corner positions — perimeter ambient light.",
          "corner_accents", params={"block": "@lantern"}),
    _room("corner_armor_stand", "Corner armour markers",
          "Iron-bar accent at each corner suggesting armour or weapons display.",
          "corner_accents", params={"block": "minecraft:iron_bars"}),
    _room("corner_bookcase", "Corner bookcase pair",
          "Bookshelf accent at each corner — library hint.",
          "corner_accents", params={"block": "@bookshelf"}),

    # ── FURNITURE / FIXTURES (12) ────────────────────────────────────────────
    _room("bench_set_perimeter", "Perimeter bench",
          "Inward-facing stair bench along all four interior walls — works as seating for any meeting space, hall or sanctuary.",
          "perimeter_bench"),
    _room("bench_set_inset", "Perimeter cushion ring",
          "Carpet cushions in a ring along the floor near the walls.",
          "cushion_set", params={"block": "@carpet"}),
    _room("side_table_set", "Central side table",
          "Single fence post with slab top at room centre — a tea or side table.",
          "center_table"),
    _room("low_table_cushions", "Low table with cushions",
          "Center fence-post table plus carpet cushions around it.",
          "cushion_set", params={"block": "@carpet"}),
    _room("bookshelf_arrangement_north", "Bookshelves on north wall",
          "Two-cell-high bookshelf wall along the -Z (north) face.",
          "row_of_shelves", params={"side": "north"}),
    _room("bookshelf_arrangement_south", "Bookshelves on south wall",
          "Two-cell-high bookshelf wall along the +Z (south) face.",
          "row_of_shelves", params={"side": "south"}),
    _room("bookshelf_arrangement_west", "Bookshelves on west wall",
          "Two-cell-high bookshelf wall along the -X (west) face.",
          "row_of_shelves", params={"side": "west"}),
    _room("weapon_rack_wall", "Weapon rack wall",
          "Iron-bar rack along the north wall — weapons or armoury display.",
          "row_of_shelves", params={"block": "minecraft:iron_bars", "side": "north"}),
    _room("divan_set", "Inward-facing divan",
          "Inward-facing stair bench along the long walls only (cushioned alternative).",
          "perimeter_bench"),
    _room("altar_pedestal", "Central altar pedestal",
          "Fence post + slab at room centre with carpet underneath — sanctuary altar.",
          "center_table", params={"post": "@accent", "top": "@slab"}),
    _room("display_case_central", "Central display case",
          "Center column of glass topped with accent block — a display case for a relic.",
          "center_table", params={"post": "@glass", "top": "@accent"}),
    _room("alcove_seat_single", "Single alcove seat",
          "One inward-facing stair tucked against the -Z wall with an accent back.",
          "alcove_seat"),

    # ── LIGHTING (10) ────────────────────────────────────────────────────────
    _room("light_band_lanterns_3", "Lantern band every 3",
          "Lanterns every third cell on the perimeter at the ceiling-1 layer — ensures even lighting.",
          "perimeter_lanterns", params={"every": 3}),
    _room("light_band_lanterns_4", "Lantern band every 4",
          "Sparser lantern band — lanterns every fourth cell for larger rooms.",
          "perimeter_lanterns", params={"every": 4}),
    _room("light_band_lanterns_2", "Dense lantern band",
          "Lanterns every second cell — bright workshop or kitchen lighting.",
          "perimeter_lanterns", params={"every": 2}),
    _room("light_pendants_grid", "Pendant grid lighting",
          "Pendant fixture at the room centre with a 2-cell drop.",
          "ceiling_center_fixture", params={"drop": 2, "light": "@lantern"}),
    _room("light_floor_lamps", "Floor lamps in corners",
          "Single tall fence post capped with lantern in each corner — floor lamps.",
          "corner_posts", params={"block": "@fence", "cap": "@lantern"}),
    _room("light_torch_pair", "Torch pair (entry)",
          "Two torches flanking the room centre on the -Z wall — entry sconces.",
          "alcove_seat", params={"seat": "@accent", "back": "minecraft:torch"}),
    _room("light_candle_circle", "Candle circle",
          "Ring of torches around the room centre — ritual gathering.",
          "candle_circle"),
    _room("light_floor_torches", "Floor torch ring",
          "Larger ring of floor torches around the perimeter.",
          "torch_ring"),
    _room("light_paper_lantern_string", "Paper lantern garland",
          "Lanterns along the long axis below the ceiling — festival garland.",
          "perimeter_lanterns", params={"every": 2, "block": "@lantern"}),
    _room("light_brazier_corners", "Corner braziers (lit)",
          "Corner posts (height 2) capped with lantern.",
          "corner_posts", params={"block": "@accent", "cap": "@lantern", "height": 2}),

    # ── ROOF DETAILS (15) ────────────────────────────────────────────────────
    _roof("roof_finial_simple", "Simple roof spire",
          "Three-block vertical mast of @accent at the centre of the roof.",
          "vertical_spire", params={"height": 3}),
    _roof("roof_finial_orb", "Roof spire with orb",
          "Mast topped with an accent orb cap.",
          "vertical_spire", params={"height": 4, "cap": "@accent"}),
    _roof("roof_finial_spike", "Tall roof spike",
          "Five-block tall accent spike on the roof.",
          "vertical_spire", params={"height": 5}),
    _roof("roof_finial_cross", "Roof cross spire",
          "Tall spike topped with secondary cap — evokes a chapel cross.",
          "vertical_spire", params={"height": 3, "cap": "@secondary"}),
    _roof("roof_ridge_band", "Roof ridge accent band",
          "Accent line of @accent along the longer roof ridge.",
          "ridge_band"),
    _roof("roof_ridge_dragon", "Decorative ridge crest",
          "Accent ridge of @secondary along the longer roof axis.",
          "ridge_band", params={"block": "@secondary"}),
    _roof("roof_chimney_cluster_2", "Two-chimney cluster",
          "Two chimneys with campfire smoke heads on the roof.",
          "chimney_cluster", params={"count": 2}),
    _roof("roof_chimney_cluster_3", "Three-chimney cluster",
          "Three chimneys clustered on the roof.",
          "chimney_cluster", params={"count": 3}),
    _roof("roof_single_chimney", "Single tall chimney",
          "One tall chimney with campfire smoke head.",
          "chimney_cluster", params={"count": 1, "height": 4}),
    _roof("roof_eave_trim", "Eave trim band",
          "Decorative band along the long roof edge.",
          "ridge_band", params={"block": "@accent"}),
    _roof("roof_cupola_small", "Small roof cupola",
          "Small windowed lantern — body + glass + cap — at the roof centre.",
          "cupola_small"),
    _roof("roof_lantern", "Roof lantern fixture",
          "Glass-and-light fixture at the roof centre.",
          "cupola_small", params={"body": "@secondary", "glass": "@glass_pane", "cap": "@lantern"}),
    _roof("roof_weathervane", "Roof weathervane",
          "Tall thin mast topped with iron bars — a weathervane silhouette.",
          "vertical_spire", params={"height": 4, "cap": "minecraft:iron_bars"}),
    _roof("roof_skylight_panel", "Roof skylight panel",
          "Glass skylight panel set into the roof (one Y below the apex).",
          "cupola_small", params={"body": "@glass", "glass": "@glass_pane", "cap": "@glass"}),
    _roof("roof_acroterion", "Acroterion ornament",
          "Triple-tall accent spire on the roof apex (Greek-style acroterion).",
          "vertical_spire", params={"height": 3, "cap": "@accent"}),

    # ── FOUNTAINS / WATER FEATURES (12) ──────────────────────────────────────
    _ext("fountain_single_basin", "Single-basin fountain",
         "Square stone basin with central spout column — classical garden fountain.",
         "fountain_single_basin"),
    _ext("fountain_tiered_classic", "Tiered classical fountain",
         "Two-tier fountain: large lower basin, smaller upper basin, jet column.",
         "fountain_tiered"),
    _ext("fountain_tiered_grand", "Grand tiered fountain",
         "Wider tiered fountain — palace forecourt scale.",
         "fountain_tiered", params={"base": "@secondary", "crown": "@accent"}),
    _ext("fountain_wall_mounted", "Wall-mounted fountain",
         "Wall fountain set against the east wall — water from a basin stair.",
         "fountain_wall_mounted"),
    _ext("fountain_koi_pond", "Koi pond",
         "Stone-rimmed water pond — koi pond style.",
         "garden_pond", params={"rim": "@accent", "water": "minecraft:water"}),
    _ext("fountain_lotus", "Lotus pond",
         "Water pond with a green lily-pad accent — lotus pond style.",
         "garden_pond", params={"rim": "@secondary", "water": "minecraft:water"}),
    _ext("fountain_pebble", "Pebble basin",
         "Shallow gravel-bordered water basin — zen pebble basin.",
         "garden_pond", params={"rim": "minecraft:cobblestone", "water": "minecraft:water"}),
    _ext("fountain_obelisk", "Obelisk fountain",
         "Single tall accent spire rising from a square basin.",
         "fountain_single_basin", params={"spout": "@accent"}),
    _ext("fountain_lion_head", "Lion-head wall fountain",
         "Wall-mounted basin fountain — classical lion-head style.",
         "fountain_wall_mounted", params={"wall": "@secondary"}),
    _ext("fountain_serpent", "Serpent fountain",
         "Wall-mounted fountain with dark stone wall — serpent or dragon themed.",
         "fountain_wall_mounted", params={"wall": "minecraft:black_concrete"}),
    _ext("water_basin_well", "Stone well basin",
         "Single-basin fountain using cobblestone rim — village well style.",
         "fountain_single_basin", params={"rim": "minecraft:cobblestone"}),
    _ext("reflective_pool", "Reflective pool",
         "Rectangular shallow pool with accent rim — a Mughal reflective pool.",
         "garden_pond"),

    # ── GARDENS (15) ─────────────────────────────────────────────────────────
    _ext("garden_formal_parterre", "Formal parterre garden",
         "Geometric parterre: hedged perimeter with poppies on grass — classical formal garden.",
         "garden_parterre"),
    _ext("garden_zen_gravel", "Karesansui gravel garden",
         "Gravel sea with three scattered stones — zen dry-landscape garden.",
         "garden_zen"),
    _ext("garden_herb", "Herb garden",
         "Grass beds with dandelions — kitchen herb garden.",
         "garden_flowerbed", params={"flowers": ("minecraft:dandelion",)}),
    _ext("garden_flower_bed", "Mixed flower bed",
         "Grass beds with rotating poppy, dandelion and blue orchid flowers.",
         "garden_flowerbed"),
    _ext("garden_hedge_maze", "Hedge maze rows",
         "Parallel oak-leaf hedges along the long axis — a simple maze.",
         "garden_hedge_rows"),
    _ext("garden_bonsai_collection", "Bonsai collection",
         "Grid of flower pots topped with oak leaves — bonsai display.",
         "garden_bonsai_collection"),
    _ext("garden_rock", "Rock garden",
         "Gravel base with scattered cobble rocks — naturalistic rock garden.",
         "garden_zen", params={"gravel": "minecraft:gravel", "rock": "minecraft:cobblestone"}),
    _ext("garden_topiary", "Topiary trees",
         "Grid of leaf-topped pots — clipped topiary.",
         "garden_bonsai_collection", params={"pot": "@accent", "leaf": "minecraft:oak_leaves"}),
    _ext("garden_lotus_pond", "Lotus pond garden",
         "Water pond with central reed (light) accent.",
         "garden_pond"),
    _ext("garden_butterfly", "Butterfly garden",
         "Mixed flower bed favouring poppies and orchids — pollinator habitat.",
         "garden_flowerbed", params={"flowers": ("minecraft:poppy", "minecraft:blue_orchid")}),
    _ext("garden_succulent", "Succulent garden",
         "Sand bed with scattered cactus-substitute accents.",
         "garden_zen", params={"gravel": "minecraft:sand", "rock": "@accent"}),
    _ext("garden_climbing_vine", "Climbing vine wall",
         "Hedge rows along the perimeter — climbing greenery.",
         "garden_hedge_rows"),
    _ext("garden_pathway_circle", "Circular path garden",
         "Concentric ring of stones laid into a grass bed.",
         "garden_flowerbed"),
    _ext("garden_shaded_arbor", "Shaded arbor",
         "Pergola arch over a small garden.",
         "pergola_arch"),
    _ext("garden_kitchen", "Kitchen garden",
         "Grass beds with edible-style flowers — kitchen garden.",
         "garden_flowerbed", params={"flowers": ("minecraft:dandelion", "minecraft:poppy")}),

    # ── EXTERIOR STRUCTURES (10) ─────────────────────────────────────────────
    _ext("pergola_arch_open", "Open pergola arch",
         "Four corner posts + roof crossbeams + oak-leaf canopy — garden pergola.",
         "pergola_arch"),
    _ext("pergola_vine", "Vine-covered pergola",
         "Pergola arch densely covered with leaves — Mediterranean vine arbour.",
         "pergola_arch"),
    _ext("gazebo_open_pavilion", "Open gazebo",
         "Closed roof + four corner posts + paved floor — garden gazebo.",
         "gazebo_open"),
    _ext("pavilion_pavement", "Pavement pavilion",
         "Same as gazebo with accent roof — open pavilion for ceremonies.",
         "gazebo_open", params={"roof": "@accent"}),
    _ext("belvedere", "Belvedere viewing pavilion",
         "Open gazebo with stone roof — a belvedere overlooking a view.",
         "gazebo_open", params={"roof": "@secondary"}),
    _ext("bandstand", "Bandstand",
         "Open pavilion on stone posts — a bandstand for music.",
         "gazebo_open", params={"post": "@accent", "floor_blk": "@floor"}),
    _ext("statue_freestanding", "Freestanding statue",
         "Stone column with accent head — a stylised garden statue on a pedestal.",
         "statue_pedestal"),
    _ext("column_pair_entry", "Column pair flanking entry",
         "Two parallel columns flanking an entry path.",
         "column_pair"),
    _ext("triumphal_arch_entry", "Triumphal arch",
         "Single freestanding arch spanning the longer axis — gateway monument.",
         "triumphal_arch"),
    _ext("ornamental_gate", "Ornamental gateway",
         "Arch with accent block frame — decorative garden gate.",
         "triumphal_arch", params={"block": "@accent"}),

    # ── PATHS / BOUNDARIES (10) ──────────────────────────────────────────────
    _ext("pathway_cobble", "Cobblestone path",
         "Single-cell-wide cobblestone path along the longer plot axis.",
         "pathway_line", params={"block": "minecraft:cobblestone"}, dims=PATH_DIMS),
    _ext("pathway_gravel", "Gravel path",
         "Gravel path along the long axis.",
         "pathway_line", params={"block": "minecraft:gravel"}, dims=PATH_DIMS),
    _ext("pathway_stepping_stones", "Stepping stones",
         "Discrete cobble stones laid as stepping stones.",
         "stepping_stones", dims=PATH_DIMS),
    _ext("pathway_with_lanterns", "Lantern-lined path",
         "Path with lantern posts on each side every three cells.",
         "pathway_with_lanterns", dims=PATH_DIMS),
    _ext("pathway_curving", "Curving stone path",
         "Stone path — stepping-stone style.",
         "stepping_stones", params={"block": "minecraft:cobblestone"}, dims=PATH_DIMS),
    _ext("boundary_picket_fence", "Picket fence boundary",
         "Low fence perimeter.",
         "boundary_wall", params={"block": "@fence"}),
    _ext("boundary_stone_wall", "Stone boundary wall",
         "Low stone wall around the perimeter.",
         "boundary_wall", params={"block": "minecraft:cobblestone_wall"}),
    _ext("boundary_hedge", "Hedge boundary",
         "Low oak-leaf hedge around the perimeter.",
         "hedge_boundary"),
    _ext("iron_railing_boundary", "Iron railing boundary",
         "Iron-bar railing around the plot edge.",
         "iron_railing"),
    _ext("balustrade_boundary", "Stone balustrade",
         "Decorative stone-wall balustrade with accent posts.",
         "boundary_wall", params={"block": "@accent"}),

    # ── ASIAN-INSPIRED UNIVERSAL (12) ────────────────────────────────────────
    _room("shoji_screen", "Shoji-style screen wall",
          "Wall lattice band of @glass_pane — a translucent shoji screen.",
          "wall_lattice", params={"block": "@glass_pane"}),
    _room("calligraphy_band_asian", "Asian calligraphy band",
          "High accent band of @secondary near the ceiling — calligraphy strip.",
          "wall_band", params={"y_frac": 0.85, "block": "@secondary"}),
    _ext("bonsai_display", "Bonsai pot display",
         "Grid of pots topped with oak leaves — bonsai display arrangement.",
         "garden_bonsai_collection"),
    _ext("karesansui_stones", "Karesansui stone arrangement",
         "Gravel sea with cobble stones — classical karesansui zen garden.",
         "garden_zen"),
    _room("chochin_string", "Hanging chochin lanterns",
          "Lanterns every other cell along the perimeter — chochin string.",
          "perimeter_lanterns", params={"every": 2}),
    _ext("bamboo_grove_corner", "Bamboo grove",
         "Tall fence-posts arranged at intervals — bamboo grove silhouette.",
         "corner_posts", params={"block": "@fence", "cap": None, "height": 5}, dims=EXT_PLOT_DIMS),
    _room("prayer_wheel", "Prayer wheel pedestal",
          "Central fence-post + lantern top — a Tibetan prayer wheel motif.",
          "center_table", params={"post": "@fence", "top": "@lantern"}),
    _room("incense_burner", "Incense burner",
          "Central column of accent capped with campfire — a censer/brazier.",
          "freestanding_column", params={"shaft": "@accent", "cap": "minecraft:campfire"},
          dims=SMALL_ROOM_DIMS),
    _room("decorative_drum", "Ceremonial drum",
          "Single block + accent topper at room centre — a temple drum.",
          "center_table", params={"post": "@accent", "top": "@accent"}),
    _ext("paifang_gate", "Paifang gate",
         "Wider triumphal arch — a Chinese paifang ceremonial gate.",
         "triumphal_arch", params={"block": "@accent"}),
    _ext("torii_lantern_path", "Torii-lined path",
         "Lantern-lined path — approach to a shrine.",
         "pathway_with_lanterns", dims=PATH_DIMS),
    _ext("zen_pavilion", "Zen tea pavilion",
         "Open gazebo with wooden roof — tea pavilion.",
         "gazebo_open", params={"roof": "@roof", "floor_blk": "@floor"}),

    # ── CLASSICAL / WESTERN MONUMENTAL (8) ───────────────────────────────────
    _ext("doric_column", "Doric column",
         "Single column of @secondary capped with @accent — Doric order.",
         "freestanding_column", params={"shaft": "@secondary", "cap": "@accent"}),
    _ext("ionic_column", "Ionic column",
         "Column with accent cap.",
         "freestanding_column", params={"shaft": "@primary", "cap": "@accent"}),
    _ext("corinthian_column", "Corinthian column",
         "Column with leafy capital (cap of oak leaves over accent).",
         "freestanding_column", params={"shaft": "@accent", "cap": "minecraft:oak_leaves"}),
    _ext("pediment_arch", "Pediment arch",
         "Triumphal arch with secondary stone — a classical pediment.",
         "triumphal_arch", params={"block": "@secondary"}),
    _ext("urn_pair", "Pair of urns",
         "Two flower-pot accents on each long-axis end — urn pair.",
         "column_pair", params={"shaft": "@flower_pot", "cap": "@flower_pot"}),
    _ext("amphora_set", "Amphora row",
         "Series of flower-pot urns along a path — amphora row.",
         "stepping_stones", params={"block": "@flower_pot"}, dims=PATH_DIMS),
    _ext("swag_drapery", "Swag drapery band",
         "Accent band along long ridge — swagged drapery silhouette.",
         "ridge_band", params={"block": "@accent"}),
    _ext("laurel_wreath", "Laurel wreath ring",
         "Ring of oak leaves at floor level — laurel wreath.",
         "candle_circle", params={"block": "minecraft:oak_leaves"}),

    # ── MISCELLANEOUS UNIVERSALS (8) ─────────────────────────────────────────
    _room("arch_opening_wall", "Arch opening",
          "Decorative arch shape framed by accent blocks on the -Z wall.",
          "arch_opening"),
    _room("balcony_railing", "Interior balcony railing",
          "Low fence railing along the room perimeter — balcony or mezzanine edge.",
          "boundary_wall", params={"block": "@fence"}),
    _room("foyer_carpet_runner", "Foyer carpet runner",
          "3-cell-wide carpet runner along the long axis — entry foyer rug.",
          "carpet_runner"),
    _room("mirror_wall_glass", "Mirror wall (glass)",
          "Full glass plane along the -Z wall — mirror or display.",
          "mirror_wall"),
    _room("alcove_seat_window", "Window alcove seat",
          "Single alcove stair seat with accent back — reading nook.",
          "alcove_seat"),
    _room("window_lattice", "Window lattice",
          "Lattice band of @glass_pane around the room mid-band — windowed lattice.",
          "wall_lattice"),
    _room("threshold_inset", "Threshold floor inset",
          "Small accent inset on the floor where an entry would be.",
          "floor_center_inset", params={"base": "@floor", "inset_blk": "@accent", "inset": 3}),
    _room("decorative_armoire", "Decorative armoire",
          "Tall column at room centre capped with bookshelf — an armoire silhouette.",
          "freestanding_column", params={"shaft": "@bookshelf", "cap": "@accent"}),
]


def count_by_family() -> dict:
    out: dict = {}
    for s in SKILLS:
        out[s["family"]] = out.get(s["family"], 0) + 1
    return out


if __name__ == "__main__":
    print(f"{len(SKILLS)} universal skills across families:")
    for fam, n in sorted(count_by_family().items()):
        print(f"  {fam:<14s} {n}")
